@echo off
echo Starting VoiceBot CUD Service on port 5000...
cd /d "%~dp0..\backend\cud_service"
echo Installing dependencies...
pip install -r requirements.txt -q
echo Starting CUD service...
uvicorn app.main:app --reload --host 0.0.0.0 --port 5000
pause
