@echo off
echo Starting VoiceBot GraphQL Service on port 5001...
cd /d "%~dp0..\backend\graphql_service"
echo Installing dependencies...
pip install -r requirements.txt -q
echo Starting GraphQL service...
uvicorn app.main:app --reload --host 0.0.0.0 --port 5001
pause
